### ISSUE TITLE
be able to change filename ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#141] opened 2018-08-24 08:58 UTC
Currently changing the filename is relatively difficult. You need to skip the attachment and add a new attachment.

Would it make sense to have also the property 

`result.filename` that by default has as value `ctx.filename` ?

This would allow to easily make filename unique as well by adding timestamp and simplify the example.

I also have some cases when the file is abc.jdx.1234 and it should be renamed in abc.X.jdx (where X can be found in the jcamp)

**Comment by targos** [comment] 2018-08-24 09:02
duplicate of https://github.com/cheminfo/rest-on-couch/issues/130

**Closed by targos** 2018-08-24 09:02 UTC
