### ISSUE TITLE
showing group memberships fails

### ISSUE THREAD

**Issue by stropitek** [cheminfo/rest-on-couch#169] opened 2018-10-31 13:24 UTC
version: 6.0.0

https://mydb.cheminfo.org/#/group_memberships

![image](https://user-images.githubusercontent.com/4118690/47790884-972c0c00-dd18-11e8-9977-789b7fefeb61.png)

**Comment by targos** [comment] 2018-10-31 16:32
We should give this UI some love. It's been a long time.

**Comment by stropitek** [comment] 2018-11-01 06:56
The problem only happens if no database is selected. The menu should not show up if no database is selected.

**Comment by targos** [comment] 2018-11-01 20:09
I can't reproduce in a dev environment. Will try again on mydb after https://github.com/cheminfo/rest-on-couch/pull/172 is merged

**Comment by targos** [comment] 2018-11-02 13:20
OK, got it. I had `autoCreateDatabase` set to true in dev

**Closed** 2018-11-02 15:54 UTC
